export default {
  LOGIN: 'login',
  REGISTER: 'register',
  HOME: 'home',
  PROFILE: 'profile',
  NOTIFICATION: 'notification',
  TAB: 'tab',
  AUTH_PHONE: 'authPhone',
  WALLET: 'wallet',
  ORDER: 'order',
  ACTIVE_SHIPPER: 'activeShipper',
  ORDER_SHIPPING: 'orderShipping',
  REPORT: 'report',
  REVIEW: 'review',
  FORGOT_PASSWORD: 'forgotPassword',
  CHECK_CODE: 'checkCode',
  UPDATE_PASSWORD: 'updatePassword',
  TRANSACTION_HISTORY: 'transactionHistory',
  ADD_BANK: 'addBank',
  WITHDRAW: 'withdraw',
  UPDATE_PROFILE: 'updateProfile',
}